version: '3.8'

services:
  web:
    build: .
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: pharmacy-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pharmacy
    volumes:
      - db_data:/var/lib/mysql
      - ./pharmacy.sql:/docker-entrypoint-initdb.d/pharmacy.sql

volumes:
  db_data:
